version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: consultation_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: consultation_platform
      POSTGRES_USER: consultation_user
      POSTGRES_PASSWORD: consultation_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U consultation_user -d consultation_platform",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  app:
    build: .
    container_name: consultation_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://consultation_user:consultation_password@postgres:5432/consultation_platform
      - ENVIRONMENT=development
      - DEBUG=true
      - SECRET_KEY=development-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
